[news]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul.news-article-list.article-list.list li.listItem"
titleSelector = "p.title a"
linkSelector = "p.title a"
contentSelector = "div.description p"
imageSelector = "div.articleImg img"
waitForSelector = "ul.news-article-list.article-list.list li.listItem"
onFail = "stale"

[magazine]
title = "무신사 ─ 매거진"
url = "https://magazine.musinsa.com/?m=magazine"
entrySelector = "ul[class='magazine-article-list article-list list'] li[class='listItem']"
titleSelector = "div.articleInfo > div.title > a:nth-child(1)"
linkSelector = "div[class='articleImg'] a"
contentSelector = "div.articleInfo p"
imageSelector = "img.lazy-load-image"
waitUntil = "networkidle"
onFail = "stale"

[lookbook]
title = "무신사 ─ 룩북"
url = "https://magazine.musinsa.com/index.php?m=lookbook&sort=dataDate&p=1"
entrySelector = "ul.boxed-article-list.lookbook-article-list.article-list.center.list li.listItem"
titleSelector = "span.brackets"
linkSelector = "div.articleImg a"
contentSelector = "div.title"
imageSelector = "div.articleImg a img"
waitUntil = "networkidle"
onFail = "stale"

[street]
title = "무신사 ─ 스트릿 스냅"
url = "https://magazine.musinsa.com/index.php?m=street&_y=2021&ordw=submitdate&p=1"
entrySelector = "ul.snap-article-list.boxed-article-list.article-list.center.list li.listItem"
titleSelector = "p.name"
linkSelector = "div.articleImg a"
contentSelector = "p.brackets.category"
imageSelector = "div.articleImg a img"
waitUntil = "networkidle"
onFail = "stale"

[shopstaff]
title = "무신사 ─ 브랜드 스냅"
url = "https://magazine.musinsa.com/index.php?m=shopstaff&_y=2021&ordw=d_regis&p=1"
entrySelector = "ul.snap-article-list.boxed-article-list.article-list.center.list li.listItem"
titleSelector = "p.name"
linkSelector = "div.articleImg a"
contentSelector = "p.brackets.brand"
imageSelector = "div.articleImg a img"
waitUntil = "networkidle"
onFail = "stale"

[recruit]
title = "무신사 ─ 구인"
url = "https://magazine.musinsa.com/?m=recruit"
entrySelector = "ul[class='recruit-article-list article-list list'] li"
titleSelector = "a.title"
linkSelector = "a[class='title']"
contentSelector = "a.brand"
imageSelector = "a.img img"
waitUntil = "networkidle"
onFail = "stale"

[tv]
title = "무신사 ─ TV"
url = "https://magazine.musinsa.com/?m=magazine&tvMode=on"
entrySelector = "ul.magazine-article-list.article-list.list li.listItem"
titleSelector = "div.title"
linkSelector = "div.title > a"
contentSelector = "p.description"
imageSelector = "div.articleImg > a > img"
waitUntil = "networkidle"
onFail = "stale"

[naverpost_musinsa_snap]
title = "네이버 포스트 ─ 무신사 ─ 무신사 스냅"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=195255&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_report]
title = "네이버 포스트 ─ 무신사 ─ 무신사 리포트"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=508128&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_stylefactory]
title = "네이버 포스트 ─ 무신사 ─ 스타일 팩토리"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=369379&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_stylelesson]
title = "네이버 포스트 ─ 무신사 ─ 스타일 레슨"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=225468&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_storerank]
title = "네이버 포스트 ─ 무신사 ─ 무신사 스토어 랭킹"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=195260&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
